controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    app_forgot_password:
        path: /forgot-password
        controller: App\Controller\Auth\AuthController::forgotPassword

    app_reset_password:
        path: /reset-password/{token}
        controller: App\Controller\Auth\AuthController::resetPassword
        requirements:
            token: .+
